# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DinDinnChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DinDinnChallenge
  pod 'ImageSlideshow/Alamofire'

  target 'DinDinnChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DinDinnChallengeUITests' do
    # Pods for testing
  end

end
